### ISSUE TITLE
(17) Employee Manage Profile 

### ISSUE THREAD

**Issue by caitlinyang** [frankiekim5/ATL_Beltline#14]
1. First Name, Last Name, Phone, Email, Visitor Account is editable
2. Visitor Account is checked if the employee is also a visitor
3. Deselecting Visitor Account and Update will erase all visit history for the employee; The employee will lose access to all visitor functionalities
4.Employee ID is a unique 9-digit number assigned to each employee once their account got approved by administrator(you can auto-generate this number)
5.Site Name is blank unless the employee is a manager

**Comment by lil-frankie** [comment]
Finished everything for this issue except for #3 (deselecting visitor account)
